version: "3"

services:
  desafio-01:
    build: .
    image: acgomes68/alpine-node:latest
    container_name: bootcamp-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - .:/usr/app
