version: "3"

services:
  desafio-02:
    build: .
    image: acgomes68/alpine-node:latest
    container_name: bootcamp-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - .:/usr/app
  # postgres:
  #   image: postgres:11
  #   container_name: database-${APP_NAME}
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWD}
  #   ports:
  #   - ${DB_PORT}:5432
